### ISSUE TITLE
Documentation: explain better `trigger` and `filter`

### ISSUE THREAD

**Issue by jacargentina** [use-hooks/react-hooks-axios#2]
By reading the docs, i cant get how do these two props works. Do they allow to trigger/NOT trigger axios under certain conditions right?

**Comment by int64ago** [comment]
Hi, sorry for the poor document, see this https://github.com/use-hooks/react-hooks-axios/pull/3, is it more clear?

**Comment by int64ago** [comment]
I'll close this, feel free to reopen it if you still have any problem :-)
