### ISSUE TITLE
Compiled file contains an extra modules

### ISSUE THREAD

**Issue by dmaklygin** [use-hooks/react-hooks-axios#20]
Version 1.2.0

Just looked at the `dist/index.js` file and noticed that file contains an extra modules, namely: axios.
I hope, you will also add a source file which I can use as module, w/o additional modules.
Thanks.

<img width="682" alt="screnshot" src="https://user-images.githubusercontent.com/1824723/56962553-8ccfbb00-6b5f-11e9-883c-421ac45dd916.png">

**Comment by int64ago** [comment]
Hi, you can do this
```js
import { axios } from '@use-hooks/axios';
```
