### ISSUE TITLE
Please provide a changelog

### ISSUE THREAD

**Issue by ThiefMaster** [use-hooks/react-hooks-axios#24]
When updating my dependencies I usually go through all packages in `npm outdated` and check what changed (always for major version bumps, but depending on the library for minor/feature releases too). Having to check the git commit history for that isn't amazing.

So it would be nice if you provided a changelog, either in the README or in a separate file.

**Comment by int64ago** [comment]
Thanks for the suggestion, CHANGELOG will come in the next release, sorry for the confusion :-)

**Comment by int64ago** [comment]
Hi, how about this: https://github.com/use-hooks/react-hooks-axios/releases/tag/v1.3.1

:-)
