### ISSUE TITLE
POST data is not passing

### ISSUE THREAD

**Issue by FabianoLothor** [use-hooks/react-hooks-axios#4]
This is not working. My request is not sending the data object.

```
  const { loading, error, response } = useAxios({
    filter: () => sent,
    method: 'POST',
    options: {
      data: {
        prop1: "value",
        prop2: "value2",
      },
    },
    trigger: sent,
    url: "myApiLink"
  });
```

**Comment by FabianoLothor** [comment]
Sample: https://codesandbox.io/s/43xw61xvv0

Seending for https://webhook.site/#/e0ce5add-c4a0-4886-a447-92554f727681/07c10c9e-2e3a-4cc4-bfea-92a4a4a15142/1

The request is sending OPTIONS, no POST.

**Comment by int64ago** [comment]
You should set correct headers in your own code instead of patching in this library, others have different usage scenario.

```diff
  const { loading, error, response } = useAxios({
    filter: () => sent,
    method: 'POST',
    options: {
      data: {
        prop1: "value",
        prop2: "value2",
      },
+     headers: {
+       'Content-Type': 'application/x-www-form-urlencoded',
+     },
    },
    trigger: sent,
    url: "myApiLink"
  });
```

**Comment by FabianoLothor** [comment]
axios.post method don't need add any header.

**Comment by int64ago** [comment]
Actually, it need.
You can read [docs](https://github.com/axios/axios#request-config).

**Comment by FabianoLothor** [comment]
When post:

`axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';`

You can read [docs](https://github.com/axios/axios#request-config).

**Comment by int64ago** [comment]
It's two things here:

> The request is sending OPTIONS, no POST.

It's because CORS issue, you can see more detail in Console of your demo.

> Actually, it need.

I mean POST method needs headers for `Content-Type` (although here's a default value, but what about i need to set it as `application/json`?)

At last, the code i given is just a example to explain why patching in this library is rejected.

**Comment by FabianoLothor** [comment]
Well i don't see why the hooks can't optimize the POST methods. I go try something setting `axios.default`.

**Comment by FabianoLothor** [comment]
API returns `Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported`

And change the content type to `application/json` sends a OPTION request, no POST. Your hook dosen't working fine.

**Comment by FabianoLothor** [comment]
Sorry man.

The problem it was with my SpringBoot API blocking OPTIONS requests.

I resolve the problem adding a line in the API config:

`configuration.setAllowedHeaders(Arrays.asList("Content-Type"));`
