### ISSUE TITLE
Not working with React 17

### ISSUE THREAD

**Issue by shirazz** [use-hooks/react-hooks-axios#41]
Demo React 17.
https://codesandbox.io/s/unruffled-rhodes-lfigt

Issue Screenshot
![image](https://user-images.githubusercontent.com/1519700/103137330-7cc80000-46e1-11eb-9f1a-94d2d295b454.png)

Same demo app when rendered using react 16.x with out any code changes will work.

**Comment by int64ago** [comment]
hi, i no longer work on it, here are some options:

 - [SWR](https://github.com/vercel/swr)
 - [React Query](https://github.com/tannerlinsley/react-query)
