### ISSUE TITLE
Cancel Request.

### ISSUE THREAD

**Issue by apenab** [use-hooks/react-hooks-axios#8]
Hi, good work guys.
I think about the implementation of canceling the request when the component is unmounted, cancel the previous request and add a type of debounce.
What do you think about this?

**Comment by int64ago** [comment]
Good propose!

After reading the [doc](https://github.com/axios/axios#cancellation), it looks ok.

**Comment by jannotti** [comment]
If this is to avoid calling setState on unmounted component, this might be simpler.
```
React.useEffect(() => {
  let didCancel = false;
 
  // ...
  // you can check didCancel
  // before running any setState
  // ...
 
  return () => {
    didCancel = true;
  };
});
```

Was recommended in discussion here: https://github.com/facebook/react/issues/14369

**Comment by int64ago** [comment]
Via 1.1.1
