### ISSUE TITLE
Rename Params

### ISSUE THREAD

**Issue by apenab** [use-hooks/react-hooks-axios#9]
I feel that the name of the `filter `parameter is a bit confusing

**Comment by int64ago** [comment]
Any idea?

**Comment by apenab** [comment]
Maybe **dispatchEffect**..??

**Comment by apenab** [comment]
I think the param `query` would look better as a `reFetch`

**Comment by int64ago** [comment]
Tanks, both `reFetch` and `forceDispatchEffect` sound semantic, I'll update in the next release!

`filter` and `query` will still exist as alias but not in document.

**Comment by int64ago** [comment]
Via 1.1.1
